"""``freeride init`` — interactive setup wizard.

Walks a new user through provider key entry, writes a `.env` file,
optionally prints the next-steps to start the gateway. Goal: cut
onboarding from "read the README, sign up for 6 providers, paste 7
exports into your shell" to one guided command.

Defaults to ``~/.freeride/.env`` for the output, with a clear note
that secrets land on disk there. The destination is ``--out`` if the
user wants something different. Empty input for any provider skips it.

The wizard is non-destructive: never overwrites an existing line for
a provider that the user didn't enter a new value for. Re-running
``freeride init`` after the first time is safe — it just adds new
keys without dropping old ones.
"""

from __future__ import annotations

import webbrowser
from pathlib import Path
from typing import Callable


# Keep in sync with cmd_serve.build_provider_registry().
# Each row: (provider id, [env var(s)], signup URL, one-line description).
_PROVIDER_PROMPTS: list[tuple[str, list[str], str, str]] = [
    (
        "openrouter",
        ["OPENROUTER_API_KEY"],
        "https://openrouter.ai/keys",
        "OpenRouter — most-tested provider, hundreds of free models",
    ),
    (
        "groq",
        ["GROQ_API_KEY"],
        "https://console.groq.com/keys",
        "Groq — fastest free Llama / Mixtral / DeepSeek-R1-distill",
    ),
    (
        "nvidia_nim",
        ["NVIDIA_API_KEY"],
        "https://build.nvidia.com",
        "NVIDIA NIM — Llama, Nemotron, embedding models",
    ),
    (
        "cloudflare_wai",
        ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"],
        "https://dash.cloudflare.com/profile/api-tokens",
        "Cloudflare Workers AI — 10K Neurons / day budget. Needs token + account_id.",
    ),
    (
        "huggingface",
        ["HF_TOKEN"],
        "https://huggingface.co/settings/tokens",
        "HuggingFace — full router catalog, $0.10/mo Free or $2/mo PRO budget",
    ),
    (
        "cerebras",
        ["CEREBRAS_API_KEY"],
        "https://cloud.cerebras.ai/platform",
        "Cerebras — fastest Llama / Qwen inference. Free tier with RPM/TPM limits.",
    ),
    (
        "ollama",
        ["OLLAMA_BASE_URL"],
        "https://ollama.com/download",
        "Ollama (local) — uses local models. Default URL: http://localhost:11434",
    ),
]


_DEFAULT_OUT = Path.home() / ".freeride" / ".env"


def _read_existing(path: Path) -> dict[str, str]:
    """Read an existing dotenv file into a dict so we can preserve
    keys the user didn't change. Comments and blank lines are dropped
    on rewrite — that's fine for a generated file.
    """
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if "=" not in s:
            continue
        k, _, v = s.partition("=")
        out[k.strip()] = v.strip()
    return out


def _write_env(path: Path, kvs: dict[str, str]) -> None:
    """Write the dotenv at ``path`` with mode 0o600 — file contains
    provider API keys, never group/world-readable.
    """
    body = [
        "# Generated by `freeride init`. Source this in your shell or",
        "# pass --env-file to your runtime.",
        "#",
        "# Re-running `freeride init` adds new keys without dropping old ones.",
        "",
    ]
    for k in sorted(kvs):
        body.append(f"{k}={kvs[k]}")
    body.append("")
    # Route through atomic_write so we get crash-safety + mode 0o600.
    from freeride.core.state import atomic_write

    atomic_write(path, "\n".join(body))


def _prompt(label: str, *, secret: bool = False, _input: Callable = input) -> str:
    """Wrap input() so tests can inject a fake. ``secret=True`` is a hint
    only — we don't suppress echo (most users want to see what they
    pasted; getpass on tty interferes with piped input).
    """
    return _input(label).strip()


def cmd_init(args, *, _input: Callable = input, _open_browser: Callable = webbrowser.open) -> int:
    out_path = Path(args.out) if args.out else _DEFAULT_OUT
    open_browsers = bool(getattr(args, "open_browser", False))

    print("FreeRide setup wizard")
    print()
    print("This will collect provider API keys and write them to:")
    print(f"  {out_path}")
    print()
    print("Empty input skips a provider. Ctrl-C aborts (no file written).")
    print()

    existing = _read_existing(out_path)
    if existing:
        present = ", ".join(sorted(set(existing) - {""}))
        print(f"existing keys in that file: {present or '(none)'}")
        print()

    new_kvs: dict[str, str] = dict(existing)  # start from current, layer changes
    any_set_this_run = False

    for provider_id, env_vars, url, description in _PROVIDER_PROMPTS:
        print(f"=== {description} ===")
        print(f"   sign up: {url}")
        if open_browsers:
            try:
                _open_browser(url)
            except Exception:
                pass
        for env_var in env_vars:
            current = existing.get(env_var, "")
            shown = (current[:6] + "..." + current[-4:]) if len(current) > 12 else ("(set)" if current else "")
            label = f"   {env_var}"
            if shown:
                label += f" [current: {shown}, press Enter to keep]"
            label += ": "
            try:
                value = _prompt(label, secret=True, _input=_input)
            except (EOFError, KeyboardInterrupt):
                print("\naborted — no file written.")
                return 1
            if value:
                new_kvs[env_var] = value
                any_set_this_run = True
        print()

    # Don't write a file if the user has nothing to write.
    if not new_kvs:
        print("no providers configured — nothing to save.")
        return 0

    _write_env(out_path, new_kvs)
    print(f"wrote {len(new_kvs)} env var{'s' if len(new_kvs) != 1 else ''} to {out_path}")
    if any_set_this_run:
        print()
        print("next steps:")
        print("  freeride serve     # gateway auto-loads ~/.freeride/.env at startup")
        print()
        print("then in another terminal:")
        print("  freeride doctor    # confirm everything's wired up")
        print("  freeride bench     # latency comparison across providers")
        # Note: only print the `source` hint if the user wrote elsewhere.
        if str(out_path) != str(_DEFAULT_OUT):
            print()
            print(f"(non-default output path — also `source {out_path}` "
                  "for shell sessions outside the gateway.)")
    else:
        print("(no new values entered — file unchanged from existing keys.)")
    return 0
